name: build readme with stats

on:
  schedule:
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: check out latest changes
        uses: actions/checkout@v3

      - name: set up node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: install node packages
        run: npm i

      - name: (Re)build README
        run: npm run build > README.md

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: 'True'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_EDITORS: 'True'
          SHOW_LANGUAGE_PER_REPO: 'False'
          SHOW_LOC_CHART: 'True'
          SYMBOL_VERSION: 3
          SHOW_LINES_OF_CODE: 'True'
          SHOW_SHORT_INFO: 'True'
          LOCALE: "en"
          SHOW_UPDATED_DATE: 'True'
          SHOW_TOTAL_CODE_TIME: 'True'
          SHOW_COMMIT: 'True'
          SHOW_DAYS_OF_WEEK: 'True'
          SHOW_LANGUAGE: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_TIMEZONE: 'Asia/Calcutta'